# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageMachine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageMachine
#	pod 'ImagePicker'
#pod 'DKImagePickerController'
pod "BSImagePicker", "~> 3.1"

  target 'ImageMachineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageMachineUITests' do
    # Pods for testing
  end

end
